### ISSUE TITLE
Plot reading

### ISSUE THREAD

**Issue by assassinsorrow** [felixbrucker/foxy-miner#1]
- OS: Windows and ubuntu

the miner is not reading all of my plot files the ones that it does read slows down the app and eventually crashes.

**Comment by assassinsorrow** [comment]
i have found the cause of the bug. i am running on a ubuntu server with the proxy and miner it seemed to be a driver issue because i tried installing the miner on a vm with no drivers and i could not reproduce the bug in that but when i install drivers the bug will start appearing , when i find the driver that is causing this i will let you know.

**Comment by felixbrucker** [comment]
Any update?

**Comment by felixbrucker** [comment]
closing here
