### ISSUE TITLE
Add support for ‘logToFile’ option

### ISSUE THREAD

**Issue by vexr** [felixbrucker/foxy-miner#135]
**Is your feature request related to a problem? Please describe.**
Looking for the ability to pull historical data from a local log file. Incorporating logToFile, logLevel, and logDir into configuration options similar to how it's implemented in Foxy-Proxy.

**Describe the solution you'd like**
Specifically, if you could add the following in an easy to parse format such as adding "Stats" to logLevel would cut down on the log file for this purpose.
[Stats] | Upstream | Block # | Best DL | Capacity | Scan Time |
For “Scan Time” a cumulative of all miners combined under each upstreams  would be appreciated! Another option would be something like "Start Time" and "End Time"

**Comment by felixbrucker** [comment]
`logToFile` is now added via https://github.com/felixbrucker/foxy-miner/pull/195
