### ISSUE TITLE
 connection outage...

### ISSUE THREAD

**Issue by swaty007** [felixbrucker/foxy-miner#209]
![image](https://user-images.githubusercontent.com/24301483/115446985-a1ac2a00-a220-11eb-844d-a41d0bee349a.png)
when i minning by foxy-minner some thimes i get error error getting mining info => connection outage
node v14.16.1
win10

**Comment by felixbrucker** [comment]
Connection outages can happen when your connection is unstable. In your screen the connection outage was for 1 sec (21:32:29 to 21:32:30).
For general support please use discord: https://discord.gg/gNHhn9y
