### ISSUE TITLE
Foxy miner won't see plots.

### ISSUE THREAD

**Issue by handsomedude** [felixbrucker/foxy-miner#267]
Installed foxy miner to pi4 Ubuntu 20.14

The setup configured fine. Checked config and the burst plots folder was configured correctly there 

But when I then run foxy, it saying no drive and no EC!

Works fine running scavenger standalone. Reads plots fine.

Plots on external windows 8tb drive.
Path=/media/Pi/External8TB/Burstplots is the set path in both my scavenger and foxy

**Comment by felixbrucker** [comment]
foxy-miner uses scav under the hood, so if it works in a standalone scav it will also work in foxy miner
Please compare the generated scav config of foxy miner with the scav config you use for standalone scav and change the foxy config accordingly

**Comment by handsomedude** [comment]
![1632174187235734305255677186187](https://user-images.githubusercontent.com/14062237/134079875-c4c10289-73c7-47e6-8d16-ae926e54fefe.jpg)

That's all I get.  I've compared the configs same plot dir line

**Comment by handsomedude** [comment]
If I use the same scav in a seperate folder with a config and run using ./scavenger,. It all runs fine. But I can only do the one coin at a time and the bhd pool saying I need to set payout address using scavenger so I can't mine with just stand alone scavenger for BHD

**Comment by handsomedude** [comment]
Finally got it working.

Foxy-miner config.
 useHddDirectIO: false   works fine reads plots.

useHddDirectIO: true. Does not read plots from drive.

But scavenger standalone app works fine with the option set to true. 

Dot know why foxy miner needs to be set to false for pi 4

**Comment by handsomedude** [comment]
.
