### ISSUE TITLE
Plots found on initial scan (config) but not when starting afterwards

### ISSUE THREAD

**Issue by itsme112358** [felixbrucker/foxy-miner#272]
Hi Felix! 
I just added a second host to my "farm" - Windows 21H1
Before starting to plot on internal devices, I plugged in the 6 external hard drives I had on my first farmer.
First off I just used the config from the other PC (lazy me) and updated the plot dirs. After I started the miner, it connects and updates with new blocks. It does not load my plots though :/
Next I tried to configure the miner from the beginning. I deleted the existing yaml, did the initial config and since the plot files are all in the root directories, it shows the sum as expected.
![image](https://user-images.githubusercontent.com/16080908/135172686-3b4ca91d-9e60-4bbe-928e-93b9bab9b433.png)
However once I start the miner, I have the same issue: Not a single plot from any of the drives is loaded.
![image](https://user-images.githubusercontent.com/16080908/135172980-455448ff-afc6-4622-bca4-a77ab709e3a8.png)
Since I have no graphics driver installed (only the Microsoft Basic device), I also tried setting the miner up in "CPU only" mode. Still nothing.
The plots themselves should be OK, I've been farming them up to this point.
I also tried copying one to an internal drive, didn't help either.
Out of desperation I even tried plotting a few new ones but those aren't found either. I don't get any error messages. I'm a bit lost here 😅

**Comment by felixbrucker** [comment]
It seems like scavenger is not starting, did you install the vcredist as mentioned in the docs?

**Comment by itsme112358** [comment]
I am so very sorry for wasting your time 🤦‍♂️
Works like a charm now 👍
