### ISSUE TITLE
weight over use-profitability!!!

### ISSUE THREAD

**Issue by PotatoChipsss** [felixbrucker/foxy-miner#31]
useprofitability is awesome, but if able to use together with weight especially for new coins and coins that you wanna set higher weight, then even more crazy awesome. We desperately need this feature!!!

**Comment by felixbrucker** [comment]
Closed with https://github.com/felixbrucker/foxy-miner/commit/34f9a04dfd2c76eac7dcb76401949344d3d5eaab
