### ISSUE TITLE
Unprofitable coin while using useprofitability:

### ISSUE THREAD

**Issue by PotatoChipsss** [felixbrucker/foxy-miner#32]
Able to set ignore mining weight below 100 to avoid wasting electricity on unprofitable coins. Also need to have a way to set weight of new coins so it doesn't accidentally get ignored too.

**Comment by felixbrucker** [comment]
Closed with https://github.com/felixbrucker/foxy-miner/commit/8b31a39c72d3ec2eb22992988ac9b206ff334398
